### ISSUE TITLE
Composing ValueProperties

### ISSUE THREAD

**Issue by siderakis** [JetBrains/jetpad-mapper#5]
I have a service that returns `ValueProperty<A>` and another service that returns `ValueProperty<B>`.

I want to create a service that returns `ValueProperty<C>` that takes as inputs `ValueProperty<A>` and `ValueProperty<B>`.

So the method signature looks like:

 `ValueProperty<C> blah(ValueProperty<A>a ,  ValueProperty<B> b);`

Whats the best way to implement this such that events propagate from the sources `a` and `b`, and when disposing `c` all listeners are cleaned up.

Thanks!

ps.

also the simpler case of mapping an `ValueProperty<A>` to `ValueProperty<C>`, is there anything like a map function built in?

`ValueProperty<C> c = a.map(theA -> aToC(theA))`

**Comment by solomatov** [comment]
Take a look at DerivedProperty class: https://github.com/JetBrains/jetpad-mapper/blob/master/model/src/main/java/jetbrains/jetpad/model/property/DerivedProperty.java

You also can take a look at Properties class with a lot of utility methods including map which you suggesed: https://github.com/JetBrains/jetpad-mapper/blob/master/model/src/main/java/jetbrains/jetpad/model/property/Properties.java

**Comment by siderakis** [comment]
Very cool, thanks!

**Comment by siderakis** [comment]
Is there anything similar to `flatmap`?

**Comment by siderakis** [comment]
`public static <SourceT, TargetT> ReadableProperty<TargetT> flatMap(final ReadableProperty<SourceT> prop, final Function<SourceT, ReadableProperty<TargetT>> f);`

**Comment by solomatov** [comment]
I close this issue. If you have more questions, just ask or write me via email.
